---
title: "Class 6 - HW"
author: "Ellice Wang (A16882742)"
format: pdf
---

```{r example code}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

> Q6. How would you generalize the original code above to work with any set of input protein structures? 

```{r q6 - homework}
# load in bio3d package
library(bio3d)

compare_bfactor <- function(kinase_input, chain_input="A", elety_input="CA") {
  # input is a 4 character protein code (e.g. "4AKE), name of a chain (e.g. "A"), and elety name (e.g. "CA")
  # output is a line graph depicting the B factor trends of the kinase
  
  # load in protein database dataframe of inputed kinase
  pdb_df <- read.pdb(kinase_input)
  
  # select the chain
  pdb_df.chain <- trim.pdb(pdb_df, chain=chain_input, elety=elety_input)
  
  # select the B factor of the chain
  pdb_df.b <- pdb_df.chain$atom$b
  
  # plot the Bfactor of the kinase
  plotb3(pdb_df.b, sse=pdb_df.chain, typ="l", ylab="Bfactor", main=paste(kinase_input, "\nchain:", chain_input, "\nelety:", elety_input))
}

# confirm that it works
default_plot <- compare_bfactor("4AKE")

chain_diff_plot <- compare_bfactor("4AKE", chain_input="B")

elety_diff_plot <- compare_bfactor("4AKE", elety_input = "CB")
```

